[workspace]
members = ["map", "smd", "qc" , "wad", "bsp", "byte_writer", "vtf", "gchimp", "gchimp-native", "gchimp-web", "mdl"]

[workspace.package]
authors = [ "Lê Hàn Minh Khang (Khang Le) <mkhangle20@gmail.com>" ]
version = "0.3.0"
edition = "2021"
