studiomdl = "./dist/studiomdl.exe"
crowbar = "./dist/CrowbarCommandLineDecomp.exe"

# Theme: "dark", "light", "default"
theme = "default"

# For Linux users:
# You need to set the WINEPREFIX here to run Crowbar and studiomdl binaries.
# By default Wine prefix path is usually located in your home directory

# Replace 'username' with your actual username:
# wineprefix = "/home/username/.wine"

# Or you can use custom Wine prefixes:
# wineprefix = "/home/khang/.local/share/wineprefixes/wine32/"
